### ISSUE TITLE
Add the PubNub presence feature

### ISSUE THREAD

**Issue by davidnub** [pubnub/rust#10]
In order to use PubNub presence in the Rust SDK, we will need to add the feature.

The endpoint that utilizes this feature can be seen here: https://www.pubnub.com/docs/pubnub-rest-api-documentation#presence

The presence feature should include the following methods:

* hereNow
* whereNow
* setState
* getState

Additionally there should be a configurable option to set the duration for a presence heartbeat call that is defined in the endpoint documentation.

**Comment by parasyte** [comment]
This also looks resolved: https://github.com/pubnub/rust/blob/2505adbf418bee4b71c78dab2e49ec8c05b04faa/pubnub-hyper/src/transport/hyper/presence.rs
