### ISSUE TITLE
Add the PubNub history feature

### ISSUE THREAD

**Issue by davidnub** [pubnub/rust#11]
In order to use the PubNub history feature, there should be added methods to the Rust SDK that will utilize the endpoints related to this feature.

The documentation for the API Endpoint for history can be seen here: https://www.pubnub.com/docs/pubnub-rest-api-documentation#history

The Rust SDK should include the following history methods:

* fetchMessages
* deleteMessages
* messageCounts

Please note that the parameters for the history methods should be clear and concise to the end user (developer) and NOT a direct translation from the API query parameters.

**Comment by parasyte** [comment]
This should be fixed now by #59
