### ISSUE TITLE
Provide a dummy Transport and Runtime in the core for documentation purposes

### ISSUE THREAD

**Issue by MOZGIII** [pubnub/rust#22]
This is partially solved by #19, which switches to using mocks instead of `pubnub_hyper` transport and runtime. We might still want to provide dummy doc-only values to simplify this.

This is only relevant for simple cases where we don't actually want to provide a real usage example. Bigger examples should still have proper full-featured documentation, but with only relevant features demonstrated.

We might as well use `todo!()` instead of the dummy transport/runtime.

**Comment by Xavrax** [comment]
Old SDK related issue - closing.
