### ISSUE TITLE
Implement type-system level enforcement for correctness of channel name values

### ISSUE THREAD

**Issue by MOZGIII** [pubnub/rust#33]
Follow up after https://github.com/pubnub/rust/pull/31#discussion_r383689692

**Comment by MOZGIII** [comment]
There is some progress: we have a proper restrictions in place for `subscribe` call. What's left is to audit the rest of the code and determine whether we can re-use the `SubscribeTo`, or if we need another way.

**Comment by Xavrax** [comment]
Old SDK related issue - closing.
