### ISSUE TITLE
Rework transport implementation for easier PAM signing

### ISSUE THREAD

**Issue by MOZGIII** [pubnub/rust#60]
To allow for reuse of the code paths for signed request flows, in addition to the regular, unsigned request flow, the `hyper` transport implementation should be reworked.

Every transport call can be split into three stages:

1. `http::Request` preparation from the input data.
2. Execution of the prepared `http::Request`; a result of that is either an HTTP-protocol level error, or a valid `http::Response`.
3. Processing of the `http::Response`; this includes status code assertion, headers and body parsing.

Steps (1) and (3) are provided by us, while step (2) is typically just a `self.http_client.request(req).await?` invocation.

We can restructure the code in such a way that (1) and (3) steps are independent composable units. This would allow us to combine the parts more elegantly, and thus solve our requirements for the PAM signatures. Alternatively, we can make step (2) implementation generic, so we can apply middlewares at that layer.

PAM signed request is a different flow from the typical, unsigned request. It logically consists of the same steps that are used in the standard request, but with an extra step of computing the signature from the request.

The signed request flow looks like this: (1) -> (\*) -> (2) -> (3), where (\*) represents a step that takes an `http::Request` prepared at the step (1), signs it and produces another `http::Request`, suitable to perform a signed request, that is later used at step (2) instead of the original one. This effectively performs the signed request reusing the most demanding manually implemented steps.

In general, the goals of the outlined code changes are:
- to avoid duplicating the code for the regular and PAM-signed request flows;
- provide an elegant user interface, such that it's easy to use plain and signed requests;
- unlock the ability to test PAM-signed requests in CI, to keep that flow continuously validated just like the regular flow.

**Comment by Xavrax** [comment]
Old SDK related issue - closing.
